Models/Abonadore.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebNinnoFeliz.Models
{
    public partial class Abonadore
    {
        public Abonadore()
        {
            AbonadorCargoMensuales = new HashSet<AbonadorCargoMensuale>();
        }

        [Key]
        [Column("idAbonador")]
        public int IdAbonador { get; set; }
        [Column("numeroCuenta")]
        public int NumeroCuenta { get; set; }
        [Column("idEncargado")]
        public int IdEncargado { get; set; }

        [ForeignKey(nameof(IdEncargado))]
        [InverseProperty(nameof(Encargado.Abonadores))]
        public virtual Encargado IdEncargadoNavigation { get; set; }
        [InverseProperty(nameof(AbonadorCargoMensuale.IdAbonadorNavigation))]
        public virtual ICollection<AbonadorCargoMensuale> AbonadorCargoMensuales { get; set; }
    }
}

Controllers/AbonadoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;
using WebNinnoFeliz.Data;
using WebNinnoFeliz.Models;

namespace WebNinnoFeliz.Controllers
{
    public class AbonadoreController : Controller
    {
        private readonly WebNinnoFelizContext _context;

        public AbonadoreController(WebNinnoFelizContext context)
        {
            _context = context;
        }


        // GET: Abonadore
        public async Task<IActionResult> Index()
        {
            var webNinnoFelizContext = _context.Abonadores.Include(a => a.IdEncargadoNavigation);
            return View(await webNinnoFelizContext.ToListAsync());
        }

        //PDF

        public async Task<IActionResult> PDF()
        {
            //return View(await _context.Parentezcos.ToListAsync());
            return new ViewAsPdf(await _context.Abonadores.Include(a => a.IdEncargadoNavigation).ToListAsync())
            {
                FileName = "Abonadores.pdf"
            };
        }

        // GET: Abonadore/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var abonadore = await _context.Abonadores
                .Include(a => a.IdEncargadoNavigation)
                .FirstOrDefaultAsync(m => m.IdAbonador == id);
            if (abonadore == null)
            {
                return NotFound();
            }

            return View(abonadore);
        }

        // GET: Abonadore/Create
        public IActionResult Create()
        {
            ViewData["IdEncargado"] = new SelectList(_context.Encargados, "IdEncargado", "IdentificacionEncargado");
            return View();
        }

        // POST: Abonadore/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdAbonador,NumeroCuenta,IdEncargado")] Abonadore abonadore)
        {
            if (ModelState.IsValid)
            {
                SqlConnection conn = (SqlConnection)_context.Database.GetDbConnection();
                SqlCommand cmd = conn.CreateCommand();
                conn.Open();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.CommandText = "sp_IngresarAbonadores";
                //cmd.Parameters.Add("@idAbonador", System.Data.SqlDbType.Int).Value = abonadore.IdAbonador;
                cmd.Parameters.Add("@numeroCuenta", System.Data.SqlDbType.Int).Value = abonadore.NumeroCuenta;
                cmd.Parameters.Add("@idEncargado", System.Data.SqlDbType.Int).Value = abonadore.IdEncargado;
                await cmd.ExecuteNonQueryAsync();
                conn.Close();
                //_context.Add(abonadore);
                //await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdEncargado"] = new SelectList(_context.Encargados, "IdEncargado", "IdentificacionEncargado", abonadore.IdEncargado);
            return View(abonadore);
        }

        // GET: Abonadore/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var abonadore = await _context.Abonadores.FindAsync(id);
            if (abonadore == null)
            {
                return NotFound();
            }
            ViewData["IdEncargado"] = new SelectList(_context.Encargados, "IdEncargado", "IdentificacionEncargado", abonadore.IdEncargado);
            return View(abonadore);
        }

        // POST: Abonadore/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdAbonador,NumeroCuenta,IdEncargado")] Abonadore abonadore)
        {
            if (id != abonadore.IdAbonador)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    SqlConnection conn = (SqlConnection)_context.Database.GetDbConnection();
                    SqlCommand cmd = conn.CreateCommand();
                    conn.Open();
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.CommandText = "sp_ModificarAbonadores";
                    cmd.Parameters.Add("@idAbonador", System.Data.SqlDbType.Int).Value = abonadore.IdAbonador;
                    cmd.Parameters.Add("@numeroCuenta", System.Data.SqlDbType.Int).Value = abonadore.NumeroCuenta;
                    cmd.Parameters.Add("@idEncargado", System.Data.SqlDbType.Int).Value = abonadore.IdEncargado;
                    await cmd.ExecuteNonQueryAsync();
                    conn.Close();
                    //_context.Add(abonadore);
                    //await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AbonadoreExists(abonadore.IdAbonador))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdEncargado"] = new SelectList(_context.Encargados, "IdEncargado", "IdentificacionEncargado", abonadore.IdEncargado);
            return View(abonadore);
        }

        // GET: Abonadore/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var abonadore = await _context.Abonadores
                .Include(a => a.IdEncargadoNavigation)
                .FirstOrDefaultAsync(m => m.IdAbonador == id);
            if (abonadore == null)
            {
                return NotFound();
            }

            return View(abonadore);
        }

        // POST: Abonadore/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            SqlConnection conn = (SqlConnection)_context.Database.GetDbConnection();
            SqlCommand cmd = conn.CreateCommand();
            conn.Open();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "sp_EliminarAbonadores";
            cmd.Parameters.Add("@idAbonador", System.Data.SqlDbType.Int).Value = id;
            await cmd.ExecuteNonQueryAsync();
            conn.Close();
            //var abonadore = await _context.Abonadores.FindAsync(id);
            //_context.Abonadores.Remove(abonadore);
            //await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AbonadoreExists(int id)
        {
            return _context.Abonadores.Any(e => e.IdAbonador == id);
        }
    }
}

Views/Abonadore/Create.cshtml
@model WebNinnoFeliz.Models.Abonadore

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Abonador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NumeroCuenta" class="control-label"></label>
                <input asp-for="NumeroCuenta" class="form-control" />
                <span asp-validation-for="NumeroCuenta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdEncargado" class="control-label"></label>
                <select asp-for="IdEncargado" class="form-control" asp-items="ViewBag.IdEncargado"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <div class="form-group">
                <a asp-action="Index" class="btn btn-dark">Back to List</a>
            </div>
        </form>
    </div>
</div>
<div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Abonadore/Delete.cshtml
@model WebNinnoFeliz.Models.Abonadore

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Abonador</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroCuenta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumeroCuenta)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdEncargadoNavigation.IdentificacionEncargado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdEncargadoNavigation.IdentificacionEncargado)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdEncargadoNavigation.NombreEncargado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdEncargadoNavigation.NombreEncargado)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdEncargadoNavigation.Apell1Encargado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdEncargadoNavigation.Apell1Encargado)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdEncargadoNavigation.Apell2Encargado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdEncargadoNavigation.Apell2Encargado)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdAbonador" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-dark">Back to List</a>
    </form>
</div>

Views/Abonadore/Details.cshtml
@model WebNinnoFeliz.Models.Abonadore

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Abonador</h4> 
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroCuenta)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumeroCuenta)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdEncargadoNavigation.IdentificacionEncargado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdEncargadoNavigation.IdentificacionEncargado)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdEncargadoNavigation.NombreEncargado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdEncargadoNavigation.NombreEncargado)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdEncargadoNavigation.Apell1Encargado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdEncargadoNavigation.Apell1Encargado)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdEncargadoNavigation.Apell2Encargado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdEncargadoNavigation.Apell2Encargado) 
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdAbonador" class="btn btn-success">Editar</a> |
    <a asp-action="Index" class="btn btn-dark">Back to List</a>
</div>

Views/Abonadore/Edit.cshtml
@model WebNinnoFeliz.Models.Abonadore

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Abonador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdAbonador" />
            <div class="form-group">
                <label asp-for="NumeroCuenta" class="control-label"></label>
                <input asp-for="NumeroCuenta" class="form-control" />
                <span asp-validation-for="NumeroCuenta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdEncargado" class="control-label"></label>
                <select asp-for="IdEncargado" class="form-control" asp-items="ViewBag.IdEncargado"></select>
                <span asp-validation-for="IdEncargado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
            <div class="form-group">
                <a asp-action="Index" class="btn btn-dark">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Abonadore/Index.cshtml
@model IEnumerable<WebNinnoFeliz.Models.Abonadore>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Tabla de Abonadores</h1>

<form asp-controller="Abonadore" asp-action="Index">
    <p>
        Busacar por Detalle: <input type="text" name="buscar" class="form-text" />
        <br />
        <input type="submit" value="Buscar" class="btn btn-sm btn-dark" />
    </p>

</form>
<p>
    <a asp-action="Create" class="btn btn-primary">Nuevo</a>
    <a asp-action="PDF" class="btn btn-primary">PDF</a>
</p>
<table class="table">
    <thead class="table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdAbonador)
            </th>
            <th>
                NumeroCuenta
            </th>
            <th>
                IdEncargado
            </th>
            <th>
                NombreEncargado
            </th>
            <th>
                Apell1Encargado
            </th>
            <th>
                Apell2Encargado
            </th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdAbonador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroCuenta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdEncargadoNavigation.IdentificacionEncargado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdEncargadoNavigation.NombreEncargado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdEncargadoNavigation.Apell1Encargado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdEncargadoNavigation.Apell2Encargado) 
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdAbonador" class="btn btn-success">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.IdAbonador" class="btn btn-info">Detalle</a> |
                <a asp-action="Delete" asp-route-id="@item.IdAbonador" class="btn btn-danger">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Abonadore/PDF.cshtml
@model IEnumerable<WebNinnoFeliz.Models.Abonadore>
@{
    ViewData["Title"] = "PDF";
    Layout = "~/Views/Shared/_Sty.cshtml";
}

<h1>Tabla de Abonadores</h1>


<table class="table">
    <thead class="table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdAbonador)
            </th>
            <th>
                NumeroCuenta
            </th>
            <th>
                IdEncargado
            </th>
            <th>
                NombreEncargado
            </th>
            <th>
                Apell1Encargado
            </th>
            <th>
                Apell2Encargado
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdAbonador)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumeroCuenta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdEncargadoNavigation.IdentificacionEncargado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdEncargadoNavigation.NombreEncargado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdEncargadoNavigation.Apell1Encargado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdEncargadoNavigation.Apell2Encargado)
                </td>
            </tr>
        }
    </tbody>
</table>