Models/Asistencia.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebNinnoFeliz.Models
{
    public partial class Asistencia
    {
        [Key]
        [Column("idAsistencia")]
        public int IdAsistencia { get; set; }
        [Column("fechaAsist", TypeName = "date")]
        public DateTime FechaAsist { get; set; }
        [Column("estadoAsist")]
        public bool EstadoAsist { get; set; }
        [Column("idNinno")]
        public int IdNinno { get; set; }

        [ForeignKey(nameof(IdNinno))]
        [InverseProperty(nameof(Ninno.Asistencia))]
        public virtual Ninno IdNinnoNavigation { get; set; }
    }
}

Controllers/AsistenciaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;
using WebNinnoFeliz.Data;
using WebNinnoFeliz.Models;

namespace WebNinnoFeliz.Controllers
{
    public class AsistenciaController : Controller
    {
        private readonly WebNinnoFelizContext _context;

        public AsistenciaController(WebNinnoFelizContext context)
        {
            _context = context;
        }

        // GET: Asistencia
        public async Task<IActionResult> Index()
        {
            var webNinnoFelizContext = _context.Asistencias.Include(a => a.IdNinnoNavigation);
            return View(await webNinnoFelizContext.ToListAsync());
        }

        //PDF

        public async Task<IActionResult> PDF()
        {
            //return View(await _context.Parentezcos.ToListAsync());
            return new ViewAsPdf(await _context.Asistencias.Include(a => a.IdNinnoNavigation).ToListAsync())
            {
                FileName = "Asistencias.pdf"
            };
        }

        // GET: Asistencia/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asistencia = await _context.Asistencias
                .Include(a => a.IdNinnoNavigation)
                .FirstOrDefaultAsync(m => m.IdAsistencia == id);
            if (asistencia == null)
            {
                return NotFound();
            }

            return View(asistencia);
        }

        // GET: Asistencia/Create
        public IActionResult Create()
        {
            ViewData["IdNinno"] = new SelectList(_context.Ninnos, "IdNinno", "IdentificacionNinno");
            return View();
        }

        // POST: Asistencia/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdAsistencia,FechaAsist,EstadoAsist,IdNinno")] Asistencia asistencia)
        {
            if (ModelState.IsValid)
            {
                SqlConnection conn = (SqlConnection)_context.Database.GetDbConnection();
                SqlCommand cmd = conn.CreateCommand();
                conn.Open();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.CommandText = "sp_IngresarAsistencias";
                cmd.Parameters.Add("@fechaAsist", System.Data.SqlDbType.Date).Value = asistencia.FechaAsist;
                cmd.Parameters.Add("@estadoAsist", System.Data.SqlDbType.Bit).Value = asistencia.EstadoAsist;
                cmd.Parameters.Add("@idNinno", System.Data.SqlDbType.Int).Value = asistencia.IdNinno;
                await cmd.ExecuteNonQueryAsync();
                conn.Close();
                //_context.Add(asistencia);
                //await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdNinno"] = new SelectList(_context.Ninnos, "IdNinno", "IdentificacionNinno", asistencia.IdNinno);
            return View(asistencia);
        }

        // GET: Asistencia/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asistencia = await _context.Asistencias.FindAsync(id);
            if (asistencia == null)
            {
                return NotFound();
            }
            ViewData["IdNinno"] = new SelectList(_context.Ninnos, "IdNinno", "IdentificacionNinno", asistencia.IdNinno);
            return View(asistencia);
        }

        // POST: Asistencia/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdAsistencia,FechaAsist,EstadoAsist,IdNinno")] Asistencia asistencia)
        {
            if (id != asistencia.IdAsistencia)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    SqlConnection conn = (SqlConnection)_context.Database.GetDbConnection();
                    SqlCommand cmd = conn.CreateCommand();
                    conn.Open();
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.CommandText = "sp_ModificarAsistencias";
                    cmd.Parameters.Add("@idAsistencia", System.Data.SqlDbType.Int).Value = asistencia.IdAsistencia;
                    cmd.Parameters.Add("@fechaAsist", System.Data.SqlDbType.Date).Value = asistencia.FechaAsist;
                    cmd.Parameters.Add("@estadoAsist", System.Data.SqlDbType.Bit).Value = asistencia.EstadoAsist;
                    cmd.Parameters.Add("@idNinno", System.Data.SqlDbType.Int).Value = asistencia.IdNinno;
                    await cmd.ExecuteNonQueryAsync();
                    conn.Close();
                    //_context.Update(asistencia);
                    //await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AsistenciaExists(asistencia.IdAsistencia))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdNinno"] = new SelectList(_context.Ninnos, "IdNinno", "IdentificacionNinno", asistencia.IdNinno);
            return View(asistencia);
        }

        // GET: Asistencia/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asistencia = await _context.Asistencias
                .Include(a => a.IdNinnoNavigation)
                .FirstOrDefaultAsync(m => m.IdAsistencia == id);
            if (asistencia == null)
            {
                return NotFound();
            }

            return View(asistencia);
        }

        // POST: Asistencia/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            SqlConnection conn = (SqlConnection)_context.Database.GetDbConnection();
            SqlCommand cmd = conn.CreateCommand();
            conn.Open();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "sp_EliminarAsistencias";
            cmd.Parameters.Add("@idAsistencia", System.Data.SqlDbType.Int).Value = id;
            await cmd.ExecuteNonQueryAsync();
            conn.Close();
            //var asistencia = await _context.Asistencias.FindAsync(id);
            //_context.Asistencias.Remove(asistencia);
            //await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AsistenciaExists(int id)
        {
            return _context.Asistencias.Any(e => e.IdAsistencia == id);
        }
    }
}

Views/Asistencia/Create.cshtml
@model WebNinnoFeliz.Models.Asistencia

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Asistencia</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FechaAsist" class="control-label"></label>
                <input asp-for="FechaAsist" class="form-control" />
                <span asp-validation-for="FechaAsist" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="EstadoAsist" /> @Html.DisplayNameFor(model => model.EstadoAsist)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="IdNinno" class="control-label"></label>
                <select asp-for="IdNinno" class ="form-control" asp-items="ViewBag.IdNinno"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-dark">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Asistencia/Delete.cshtml
@model WebNinnoFeliz.Models.Asistencia

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Asistencia</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaAsist)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaAsist)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EstadoAsist)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EstadoAsist)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.IdentificacionNinno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNinnoNavigation.IdentificacionNinno)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.NombreNinno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNinnoNavigation.NombreNinno)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.Apell1Ninno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNinnoNavigation.Apell1Ninno)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.Apell2Ninno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNinnoNavigation.Apell2Ninno)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdAsistencia" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-dark">Back to List</a>
    </form>
</div>

Views/Asistencia/Details.cshtml
@model WebNinnoFeliz.Models.Asistencia

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Asistencia</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaAsist)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaAsist)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EstadoAsist)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EstadoAsist)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.IdentificacionNinno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNinnoNavigation.IdentificacionNinno)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.NombreNinno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNinnoNavigation.NombreNinno)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.Apell1Ninno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNinnoNavigation.Apell1Ninno)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.Apell2Ninno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNinnoNavigation.Apell2Ninno)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdAsistencia"class="btn btn-success">Editar</a> |
    <a asp-action="Index" class="btn btn-dark">Back to List</a>
</div>

Views/Asistencia/Edit.cshtml
@model WebNinnoFeliz.Models.Asistencia

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Asistencia</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdAsistencia" />
            <div class="form-group">
                <label asp-for="FechaAsist" class="control-label"></label>
                <input asp-for="FechaAsist" class="form-control" />
                <span asp-validation-for="FechaAsist" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="EstadoAsist" /> @Html.DisplayNameFor(model => model.EstadoAsist)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="IdNinno" class="control-label"></label>
                <select asp-for="IdNinno" class="form-control" asp-items="ViewBag.IdNinno"></select>
                <span asp-validation-for="IdNinno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-dark">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Asistencia/Index.cshtml
@model IEnumerable<WebNinnoFeliz.Models.Asistencia>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Tabla de asistencia</h1>

<form asp-controller="Asistencia" asp-action="Index">
    <p>
        Busacar por Detalle: <input type="text" name="buscar" class="form-text" />
        <br />
        <input type="submit" value="Buscar" class="btn btn-sm btn-dark" />
    </p>

</form>
<p>
    <a asp-action="Create" class="btn btn-primary">Nuevo</a>
    <a asp-action="PDF" class="btn btn-primary">PDF</a>
</p>
<table class="table">
    <thead class="table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdAsistencia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaAsist) 
            </th>
            <th>
                Estado
            </th>
            <th>
                Identificacion
            </th>
            <th>
                NombreNiño
            </th>
            <th>
                Apellido1Niño
            </th>
            <th>
                Apellido2Niño
            </th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdAsistencia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaAsist)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstadoAsist)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNinnoNavigation.IdentificacionNinno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNinnoNavigation.NombreNinno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNinnoNavigation.Apell1Ninno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNinnoNavigation.Apell2Ninno)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdAsistencia" class="btn btn-success">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.IdAsistencia" class="btn btn-info">Detalle</a> |
                <a asp-action="Delete" asp-route-id="@item.IdAsistencia" class="btn btn-danger">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Asistencia/PDF.cshtml
@model IEnumerable<WebNinnoFeliz.Models.Asistencia> 
@{
    ViewData["Title"] = "PDF";
    Layout = "~/Views/Shared/_Sty.cshtml";
}

<h1>Reporte de Asistencias</h1>

<table class="table">
    <thead class="table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdAsistencia) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaAsist)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstadoAsist)
            </th>
              <th>
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.IdentificacionNinno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.NombreNinno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.Apell1Ninno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.Apell2Ninno)
        </th>   
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdAsistencia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaAsist)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstadoAsist)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNinnoNavigation.IdentificacionNinno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNinnoNavigation.NombreNinno)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.IdNinnoNavigation.Apell1Ninno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdNinnoNavigation.Apell2Ninno) 
        </td> 
        </tr>
        }
    </tbody>
</table>