Models/Matricula.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebNinnoFeliz.Models
{
    public partial class Matricula
    {
        public Matricula()
        {
            EncargadoMatriculas = new HashSet<EncargadoMatricula>();
        }

        [Key]
        [Column("numeroMatricula")]
        public int NumeroMatricula { get; set; }
        [Column("fechaIngreso", TypeName = "date")]
        public DateTime FechaIngreso { get; set; }
        [Column("idNinno")]
        public int IdNinno { get; set; }

        [ForeignKey(nameof(IdNinno))]
        [InverseProperty(nameof(Ninno.Matriculas))]
        public virtual Ninno IdNinnoNavigation { get; set; }
        [InverseProperty(nameof(EncargadoMatricula.NumeroMatriculaNavigation))]
        public virtual ICollection<EncargadoMatricula> EncargadoMatriculas { get; set; }
    }
}

Controllers/MatriculaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;
using WebNinnoFeliz.Data;
using WebNinnoFeliz.Models;

namespace WebNinnoFeliz.Controllers
{
    public class MatriculaController : Controller
    {
        private readonly WebNinnoFelizContext _context;

        public MatriculaController(WebNinnoFelizContext context)
        {
            _context = context;
        }

        // GET: Matricula
        public async Task<IActionResult> Index()
        {
            var webNinnoFelizContext = _context.Matriculas.Include(m => m.IdNinnoNavigation);
            return View(await webNinnoFelizContext.ToListAsync());
        }

        //PDF

        public async Task<IActionResult> PDF()
        {
            //return View(await _context.Parentezcos.ToListAsync());
            return new ViewAsPdf(await _context.Matriculas.Include(m => m.IdNinnoNavigation).ToListAsync())
            {
                FileName = "Matricula.pdf"
            };
        }

        // GET: Matricula/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var matricula = await _context.Matriculas
                .Include(m => m.IdNinnoNavigation)
                .FirstOrDefaultAsync(m => m.NumeroMatricula == id);
            if (matricula == null)
            {
                return NotFound();
            }

            return View(matricula);
        }

        // GET: Matricula/Create
        public IActionResult Create()
        {
            ViewData["IdNinno"] = new SelectList(_context.Ninnos, "IdNinno", "IdentificacionNinno");
            return View();
        }

        // POST: Matricula/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NumeroMatricula,FechaIngreso,IdNinno")] Matricula matricula)
        {
            if (ModelState.IsValid)
            {
                SqlConnection conn = (SqlConnection)_context.Database.GetDbConnection();
                SqlCommand cmd = conn.CreateCommand();
                conn.Open();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.CommandText = "sp_IngresarMatriculas";
                cmd.Parameters.Add("@fechaIngreso", System.Data.SqlDbType.Date).Value = matricula.FechaIngreso;
                cmd.Parameters.Add("@idNinno", System.Data.SqlDbType.Int).Value = matricula.IdNinno;
                await cmd.ExecuteNonQueryAsync();
                conn.Close();
                //_context.Add(matricula);
                //await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdNinno"] = new SelectList(_context.Ninnos, "IdNinno", "IdentificacionNinno", matricula.IdNinno);
            return View(matricula);
        }

        // GET: Matricula/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var matricula = await _context.Matriculas.FindAsync(id);
            if (matricula == null)
            {
                return NotFound();
            }
            ViewData["IdNinno"] = new SelectList(_context.Ninnos, "IdNinno", "IdentificacionNinno", matricula.IdNinno);
            return View(matricula);
        }

        // POST: Matricula/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NumeroMatricula,FechaIngreso,IdNinno")] Matricula matricula)
        {
            if (id != matricula.NumeroMatricula)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    SqlConnection conn = (SqlConnection)_context.Database.GetDbConnection();
                    SqlCommand cmd = conn.CreateCommand();
                    conn.Open();
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.CommandText = "sp_ModificarMatriculas";
                    cmd.Parameters.Add("@numeroMatricula", System.Data.SqlDbType.Int).Value = matricula.NumeroMatricula;
                    cmd.Parameters.Add("@fechaIngreso", System.Data.SqlDbType.Date).Value = matricula.FechaIngreso;
                    cmd.Parameters.Add("@idNinno", System.Data.SqlDbType.Int).Value = matricula.IdNinno;
                    await cmd.ExecuteNonQueryAsync();
                    conn.Close();
                    //_context.Update(matricula);
                    //await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MatriculaExists(matricula.NumeroMatricula))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdNinno"] = new SelectList(_context.Ninnos, "IdNinno", "IdentificacionNinno", matricula.IdNinno);
            return View(matricula);
        }

        // GET: Matricula/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var matricula = await _context.Matriculas
                .Include(m => m.IdNinnoNavigation)
                .FirstOrDefaultAsync(m => m.NumeroMatricula == id);
            if (matricula == null)
            {
                return NotFound();
            }

            return View(matricula);
        }

        // POST: Matricula/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            SqlConnection conn = (SqlConnection)_context.Database.GetDbConnection();
            SqlCommand cmd = conn.CreateCommand();
            conn.Open();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "sp_EliminarMatriculas";
            cmd.Parameters.Add("@numeroMatricula", System.Data.SqlDbType.Int).Value = id;
            await cmd.ExecuteNonQueryAsync();
            conn.Close();
            //var matricula = await _context.Matriculas.FindAsync(id);
            //_context.Matriculas.Remove(matricula);
            //await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MatriculaExists(int id)
        {
            return _context.Matriculas.Any(e => e.NumeroMatricula == id);
        }
    }
}

Views/Matricula/Delete.cshtml
@model WebNinnoFeliz.Models.Matricula

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Matricula</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.IdentificacionNinno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNinnoNavigation.IdentificacionNinno)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.NombreNinno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNinnoNavigation.NombreNinno)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.Apell1Ninno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNinnoNavigation.Apell1Ninno)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.Apell2Ninno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNinnoNavigation.Apell2Ninno)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="NumeroMatricula" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-dark">Back to List</a>
    </form>
</div>

Views/Matricula/Details.cshtml
@model WebNinnoFeliz.Models.Matricula

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Matricula</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.IdentificacionNinno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNinnoNavigation.IdentificacionNinno)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.NombreNinno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNinnoNavigation.NombreNinno)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.Apell1Ninno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNinnoNavigation.Apell1Ninno)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.Apell2Ninno)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdNinnoNavigation.Apell2Ninno)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.NumeroMatricula" class="btn btn-success">Editar</a> |
    <a asp-action="Index" class="btn btn-dark">Back to List</a>
</div>

Views/Matricula/Edit.cshtml
@model WebNinnoFeliz.Models.Matricula

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Matricula</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="NumeroMatricula" />
            <div class="form-group">
                <label asp-for="FechaIngreso" class="control-label"></label>
                <input asp-for="FechaIngreso" class="form-control" />
                <span asp-validation-for="FechaIngreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNinno" class="control-label"></label>
                <select asp-for="IdNinno" class="form-control" asp-items="ViewBag.IdNinno"></select>
                <span asp-validation-for="IdNinno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-dark">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Matricula/Index.cshtml
@model IEnumerable<WebNinnoFeliz.Models.Matricula>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Tabla de matricula</h1>

<form asp-controller="Matricula" asp-action="Index">
    <p>
        Busacar por Detalle: <input type="text" name="buscar" class="form-text" />
        <br />
        <input type="submit" value="Buscar" class="btn btn-sm btn-dark" />
    </p>

</form>
<p>
    <a asp-action="Create" class="btn btn-primary">Nuevo</a>
    <a asp-action="PDF" class="btn btn-primary">PDF</a>
</p>
<table class="table">
    <thead class="table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumeroMatricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaIngreso)
            </th>
            <th>
                Identificacion Niño
            </th>
            <th>
                Nombre niño
            </th>
            <th>
                Apellido1 niño
            </th>
            <th>
                Apellido2 niño
            </th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroMatricula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaIngreso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNinno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNinnoNavigation.NombreNinno) 
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNinnoNavigation.Apell1Ninno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNinnoNavigation.Apell2Ninno)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.NumeroMatricula" class="btn btn-success">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.NumeroMatricula" class="btn btn-info">Detalle</a> |
                <a asp-action="Delete" asp-route-id="@item.NumeroMatricula" class="btn btn-danger">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Matricula/PDF.cshtml
@model IEnumerable<WebNinnoFeliz.Models.Matricula> 
@{
    ViewData["Title"] = "PDF";
    Layout = "~/Views/Shared/_Sty.cshtml";
}

<h1>Reporte Matricula</h1>

<table class="table">
    <thead class="table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumeroMatricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaIngreso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdNinnoNavigation.IdentificacionNinno) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdNinnoNavigation.NombreNinno) 
            </th>
        <th>
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.Apell1Ninno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdNinnoNavigation.Apell2Ninno)
        </th>  
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroMatricula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaIngreso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNinnoNavigation.IdentificacionNinno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdNinnoNavigation.NombreNinno)
            </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdNinnoNavigation.Apell1Ninno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdNinnoNavigation.Apell2Ninno) 
        </td>  
        </tr>
        }
    </tbody>
</table>